name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Remove existing container
      run: docker ps --quiet --filter="name=frontend" | xargs --no-run-if-empty docker rm -f
    - name: Remove existing container
      run: docker run -dt -p 80:80 --restart always --name frontend frontend
